CC.Romaji = {
    "a":      "あ",
    "ba":     "ば",
    "be":     "べ",
    "bi":     "び",
    "bo":     "ぼ",
    "bu":     "ぶ",
    "bya":    "びゃ",
    "bye":    "びぇ",
    "byi":    "びぃ",
    "byo":    "びょ",
    "byu":    "びゅ",
    "cha":    "ちゃ",
    "che":    "ちぇ",
    "chi":    "ち",
    "cho":    "ちょ",
    "chu":    "ちゅ",
    "da":     "だ",
    "de":     "で",
    "dha":    "でゃ",
    "dhe":    "でぇ",
    "dhi":    "でぃ",
    "dho":    "でょ",
    "dhu":    "でゅ",
    "di":     "ぢ",
    "do":     "ど",
    "du":     "づ",
    "dya":    "ぢゃ",
    "dye":    "ぢぇ",
    "dyi":    "ぢぃ",
    "dyo":    "ぢょ",
    "dyu":    "でゅ",
    "e":      "え",
    "fa":     "ふぁ",
    "fe":     "ふぇ",
    "fi":     "ふぃ",
    "fo":     "ふぉ",
    "fuxyu":  "ふゅ",
    "fu":     "ふ",
    "ga":     "が",
    "ge":     "げ",
    "gi":     "ぎ",
    "go":     "ご",
    "gu":     "ぐ",
    "gya":    "ぎゃ",
    "gye":    "ぎぇ",
    "gyi":    "ぎぃ",
    "gyo":    "ぎょ",
    "gyu":    "ぎゅ",
    "ha":     "は",
    "he":     "へ",
    "hi":     "ひ",
    "ho":     "ほ",
    "hu":     "ふ",
    "hya":    "ひゃ",
    "hye":    "ひぇ",
    "hyi":    "ひぃ",
    "hyo":    "ひょ",
    "hyu":    "ひゅ",
    "i":      "い",
    "ja":     "じゃ",
    "je":     "じぇ",
    "ji":     "じ",
    "jo":     "じょ",
    "ju":     "じゅ",
    "ka":     "か",
    "ke":     "け",
    "ki":     "き",
    "ko":     "こ",
    "ku":     "く",
    "kya":    "きゃ",
    "kye":    "きぇ",
    "kyi":    "きぃ",
    "kyo":    "きょ",
    "kyu":    "きゅ",
    "ma":     "ま",
    "me":     "め",
    "mi":     "み",
    "mo":     "も",
    "mu":     "む",
    "mya":    "みゃ",
    "mye":    "みぇ",
    "myi":    "みぃ",
    "myo":    "みょ",
    "myu":    "みゅ",
    "#n'":    "ん",
    "nn":     "ん",
    "na":     "な",
    "ne":     "ね",
    "ni":     "に",
    "no":     "の",
    "nu":     "ぬ",
    "nya":    "にゃ",
    "nye":    "にぇ",
    "nyi":    "にぃ",
    "nyo":    "にょ",
    "nyu":    "にゅ",
    "o":      "お",
    "pa":     "ぱ",
    "pe":     "ぺ",
    "pi":     "ぴ",
    "po":     "ぽ",
    "pu":     "ぷ",
    "pya":    "ぴゃ",
    "pye":    "ぴぇ",
    "pyi":    "ぴぃ",
    "pyo":    "ぴょ",
    "pyu":    "ぴゅ",
    "ra":     "ら",
    "re":     "れ",
    "ri":     "り",
    "ro":     "ろ",
    "ru":     "る",
    "rya":    "りゃ",
    "rye":    "りぇ",
    "ryi":    "りぃ",
    "ryo":    "りょ",
    "ryu":    "りゅ",
    "sa":     "さ",
    "se":     "せ",
    "sha":    "しゃ",
    "she":    "しぇ",
    "shi":    "し",
    "sho":    "しょ",
    "shu":    "しゅ",
    "si":     "し",
    "so":     "そ",
    "su":     "す",
    "sya":    "しゃ",
    "sye":    "しぇ",
    "syi":    "しぃ",
    "syo":    "しょ",
    "syu":    "しゅ",
    "ta":     "た",
    "te":     "て",
    "tha":    "てゃ",
    "the":    "てぇ",
    "thi":    "てぃ",
    "tho":    "てょ",
    "thu":    "てゅ",
    "ti":     "ち",
    "to":     "と",
    "tsu":    "つ",
    "tu":     "つ",
    "tya":    "ちゃ",
    "tye":    "ちぇ",
    "tyi":    "ちぃ",
    "tyo":    "ちょ",
    "tyu":    "ちゅ",
    "u":      "う",
    "va":     "う゛ぁ",
    "ve":     "う゛ぃ",
    "vi":     "う゛ぅ",
    "vo":     "う゛ぉ",
    "vu":     "う゛",
    "wa":     "わ",
    "we":     "うぇ",
    "wi":     "うぃ",
    "wo":     "を",
    "xa":     "ぁ",
    "xe":     "ぇ",
    "xi":     "ぃ",
    "xo":     "ぉ",
    "xtu":    "っ",
    "xtsu":   "っ",
    "xu":     "ぅ",
    "xwa":    "ゎ",
    "ya":     "や",
    "yo":     "よ",
    "yu":     "ゆ",
    "za":     "ざ",
    "ze":     "ぜ",
    "zi":     "じ",
    "zo":     "ぞ",
    "zu":     "ず",
    "zya":    "じゃ",
    "zye":    "じぇ",
    "zyi":    "じぃ",
    "zyo":    "じょ",
    "zyu":    "じゅ",
    "xya":    "ゃ",
    "xyu":    "ゅ",
    "xyo":    "ょ",
    "-":      "ー",
    "le":     "ぇ"
};

CC.Kanna = {};
CC.Kanna.romajiToHiragana = function(romaji) {
    romaji = romaji.toLowerCase();
    var hiragana = "";
    var i = 0;
    var staged = "";
    for (var i = 0; i < romaji.length; i++) {
        staged += romaji[i];
        var c = CC.Romaji[staged];
        if (c) {
            hiragana += c;
            staged = "";
        } else {
            var s0 = staged[0];
            var s1 = staged[1];
            var next_staged = staged.substr(1);
            if (s0 == "n" && ("bcdfghjklmnpqrstvwxz".indexOf(s1) > -1 || !s1)) {
                hiragana += "ん";
                staged = next_staged;
            } else if ("bcdfghjklmpqrstvwxyz".indexOf(s0) > -1 && s0 === s1) {
                hiragana += "っ";
                staged = next_staged;
            } else if (s1 && CC.Romaji[next_staged]) {
                hiragana += s0 + CC.Romaji[next_staged];
                staged = "";
            }
        }
    }
    if (staged.length > 0) {
        hiragana += staged;
    }
    return hiragana;
};